Add a webconfig for each of the web component product's endpoints. Ad…
IgniteUI/ig-typedoc-theme pull request #21
Opened 2023-11-29 15:35 UTC by MayaKirova

…d handling to use the related config base on option.

Depends on https://github.com/IgniteUI/typedoc-plugin-localization/pull/75

Related to: https://github.com/IgniteUI/igniteui-webcomponents/issues/991#issuecomment-1831754915

2024-01-05 15:12 UTC, mddragnev requested changes
all webcomponents files should be named as follow:
---.dockmanager.config.json
---.licensed.config.json
---.oss.config.json
because there is a webpack config that looks for ---.config files when building
```
new CopyPlugin({
            patterns: [
                {
                    context: path.resolve(__dirname),
                    from: "*config.json",
                    to: path.resolve(__dirname, "dist"),
                },
            ],
        }),
```
Currently, the tree webcomponents configs are not coppied in the dist folder when built.

2024-01-05 15:14 UTC, mddragnev commented
Also, I have an error when trying to build the angular docs:
![Screenshot 2024-01-05 at 17 12 45](https://github.com/IgniteUI/ig-typedoc-theme/assets/37667452/3274871f-1766-4970-9f47-e4ccec34d133)

It seems to be something around the reading of the produced filePath:
```
    const config = JSON.parse(fs.readFileSync(filePath, 'utf8'));
```

2024-01-08 11:10 UTC, mddragnev approved these changes

2024-01-08 17:44 UTC, skrustev approved these changes

2024-01-09 12:46 UTC, dobromirts approved these changes

2024-01-10 08:00 UTC, simeonoff approved these changes

2024-01-10 08:00 UTC, merged