build(deps): bump typedoc version to 0.26.2
IgniteUI/ig-typedoc-theme pull request #25
Opened 2024-06-27 07:35 UTC by simeonoff

Closes #24

2024-06-27 08:22 UTC, rkaraivanov approved these changes

2024-06-27 10:50 UTC, rkaraivanov commented
@simeonoff 
Seems to blow up with `flags.map is not a function`

2024-06-27 13:21 UTC, simeonoff commented
> @simeonoff Seems to blow up with `flags.map is not a function`

What blows up?

2024-06-28 07:24 UTC, rkaraivanov requested changes

2024-06-28 07:24 UTC, rkaraivanov commented on package.json
>    "peerDependecies": {
```suggestion
  "peerDependencies": {
```
Yeah, maybe we can fix that 👀

2024-06-28 07:41 UTC, rkaraivanov approved these changes

2024-06-28 07:41 UTC, merged